/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pharmacie.Graphique;

import Pharmacie.DAO.PrescriptionDAO;
import Pharmacie.metier.Prescription;
import javax.swing.JOptionPane;

/**
 *
 * @author hugo.delmarche
 */
public class CreaPres extends javax.swing.JPanel {

    PrescriptionDAO presdao = null;

    /**
     * Creates new form CreaMed2
     */
    public CreaPres() {
        initComponents();
        txtIdPres.setEditable(false);
    }

    public void setPresdao(PrescriptionDAO presdao) {
        this.presdao = presdao;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        IdPres = new javax.swing.JLabel();
        DatePres = new javax.swing.JLabel();
        IdentifMed = new javax.swing.JLabel();
        IdentifPat = new javax.swing.JLabel();
        txtIdPres = new javax.swing.JTextField();
        txtDatePres = new javax.swing.JTextField();
        txtidentifMed = new javax.swing.JTextField();
        txtIdentifPat = new javax.swing.JTextField();
        btCreaPres = new javax.swing.JButton();
        btFin = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        IdPres.setText("identifiant");

        DatePres.setText("Date prescription");

        IdentifMed.setText("Identifiant Médecin");

        IdentifPat.setText("Identifiant Patient");

        txtIdentifPat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdentifPatActionPerformed(evt);
            }
        });

        btCreaPres.setText("Création");
        btCreaPres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCreaPresActionPerformed(evt);
            }
        });

        btFin.setText("Quitter");
        btFin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFinActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btCreaPres)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(IdPres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(DatePres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(IdentifMed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(IdentifPat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 191, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtIdPres, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                    .addComponent(txtDatePres)
                    .addComponent(txtidentifMed)
                    .addComponent(txtIdentifPat)
                    .addComponent(btFin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(71, 71, 71))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(IdPres)
                    .addComponent(txtIdPres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDatePres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DatePres))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(IdentifMed)
                    .addComponent(txtidentifMed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IdentifPat)
                    .addComponent(txtIdentifPat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCreaPres)
                    .addComponent(btFin))
                .addGap(44, 44, 44))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btCreaPresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCreaPresActionPerformed
        try {
            String date = txtDatePres.getText();
            int identifmed = Integer.parseInt(txtidentifMed.getText());
            int identifpat = Integer.parseInt(txtIdentifPat.getText());
            Prescription pres = new Prescription(0, date, identifmed, identifpat);
            pres = presdao.create(pres);
            txtIdPres.setText("" + pres.getIdpres());
            JOptionPane.showMessageDialog(this, "Prescription créé", "succès", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "ERREUR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btCreaPresActionPerformed

    private void txtIdentifPatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdentifPatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdentifPatActionPerformed

    private void btFinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFinActionPerformed
        JOptionPane.showMessageDialog(this, "Au revoir", "Fermeture", JOptionPane.INFORMATION_MESSAGE);
        System.exit(0);
    }//GEN-LAST:event_btFinActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DatePres;
    private javax.swing.JLabel IdPres;
    private javax.swing.JLabel IdentifMed;
    private javax.swing.JLabel IdentifPat;
    private javax.swing.JButton btCreaPres;
    private javax.swing.JButton btFin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtDatePres;
    private javax.swing.JTextField txtIdPres;
    private javax.swing.JTextField txtIdentifPat;
    private javax.swing.JTextField txtidentifMed;
    // End of variables declaration//GEN-END:variables
}
