/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Pharmacie.Graphique;

import Pharmacie.DAO.MedecinDAO;
import java.awt.CardLayout;
import java.sql.Connection;
import javax.swing.JOptionPane;
import myconnections.DBConnection;
import javax.swing.Icon;
import javax.swing.ImageIcon;

public class GestionPharma extends javax.swing.JFrame {
    CardLayout cardl;
    
    
    /**
     * Creates new form GestionPharma
     */
    public GestionPharma() {
        initComponents();
        cardl=(CardLayout)this.getContentPane().getLayout();
        Connection dbConnect = DBConnection.getConnection();
        if (dbConnect == null) {
            System.out.println("connection invalide");
            JOptionPane.showMessageDialog(this,"connexion invalide","ERREUR",JOptionPane.ERROR_MESSAGE);
        }
        
        MedecinDAO medecinDAO = new MedecinDAO();
        medecinDAO.setConnection(dbConnect);
        creaMed21.setMeddao(medecinDAO);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        creaMed21 = new Pharmacie.Graphique.CreaMed2();
        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuMed = new javax.swing.JMenu();
        MenuMedCrea = new javax.swing.JMenuItem();
        RechMed = new javax.swing.JMenuItem();
        MenuPat = new javax.swing.JMenu();
        MenuPres = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());
        getContentPane().add(jPanel1, "card2");

        MenuMed.setText("Médecin");

        MenuMedCrea.setText("Creation");
        MenuMedCrea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuMedCreaActionPerformed(evt);
            }
        });
        MenuMed.add(MenuMedCrea);

        RechMed.setText("Recherche");
        RechMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RechMedActionPerformed(evt);
            }
        });
        MenuMed.add(RechMed);

        jMenuBar1.add(MenuMed);

        MenuPat.setText("Patient");
        jMenuBar1.add(MenuPat);

        MenuPres.setText("Prescription");
        jMenuBar1.add(MenuPres);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuMedCreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuMedCreaActionPerformed
        cardl.show(this.getContentPane(), "cardCreaMed");
    }//GEN-LAST:event_MenuMedCreaActionPerformed

    private void RechMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RechMedActionPerformed
        cardl.show(this.getContentPane(), "cardRechMed");
    }//GEN-LAST:event_RechMedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionPharma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionPharma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionPharma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionPharma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionPharma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuMed;
    private javax.swing.JMenuItem MenuMedCrea;
    private javax.swing.JMenu MenuPat;
    private javax.swing.JMenu MenuPres;
    private javax.swing.JMenuItem RechMed;
    private Pharmacie.Graphique.CreaMed2 creaMed21;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
