/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pharmacie.Graphique;

import Pharmacie.DAO.MedecinDAO;
import Pharmacie.DAO.PatientDAO;
import Pharmacie.DAO.PrescriptionDAO;
import java.awt.CardLayout;
import java.sql.Connection;
import javax.swing.JOptionPane;
import myconnections.DBConnection;

public class GestionPharma extends javax.swing.JFrame {

    static MenuPrinc mp = new MenuPrinc();
    static GestionPharma gp = new GestionPharma();
    static CardLayout cardl;

    /**
     * Creates new form GestionPharma
     */
    public GestionPharma() {
        initComponents();
        cardl = (CardLayout) this.getContentPane().getLayout();
        Connection dbConnect = DBConnection.getConnection();
        if (dbConnect == null) {
            System.out.println("connection invalide");
            JOptionPane.showMessageDialog(this, "connexion invalide", "ERREUR", JOptionPane.ERROR_MESSAGE);
        }

        MedecinDAO medecinDAO = new MedecinDAO();
        medecinDAO.setConnection(dbConnect);
        PrescriptionDAO presdao = new PrescriptionDAO();
        presdao.setConnection(dbConnect);
        PatientDAO patdao = new PatientDAO();
        patdao.setConnection(dbConnect);
        creaMed23.setMeddao(medecinDAO);
        rechMed1.setMeddao(medecinDAO);
        rechMedNom1.setMeddao(medecinDAO);
        rechMedNom1.setPresdao(presdao);
        creaPat1.setPatdao(patdao);
        rechPat1.setPatdao(patdao);
        rechPatNom1.setPatdao(patdao);
        rechPatNom1.setPresdao(presdao);
        rechPres1.setPresdao(presdao);
        creaPres1.setPresdao(presdao);
        rechNomPat1.setPatdao(patdao);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        creaMed23 = new Pharmacie.Graphique.CreaMed2();
        menuPrinc1 = new Pharmacie.Graphique.MenuPrinc();
        rechMed1 = new Pharmacie.Graphique.RechMed();
        rechMedNom1 = new Pharmacie.Graphique.RechMedNom();
        creaPat1 = new Pharmacie.Graphique.CreaPat();
        creaPres1 = new Pharmacie.Graphique.CreaPres();
        rechPat1 = new Pharmacie.Graphique.RechPat();
        rechPatNom1 = new Pharmacie.Graphique.RechPatNom();
        rechPres1 = new Pharmacie.Graphique.RechPres();
        rechNomPat1 = new Pharmacie.Graphique.RechNomPat();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuMed = new javax.swing.JMenu();
        MenuMedCrea = new javax.swing.JMenuItem();
        RechMed = new javax.swing.JMenuItem();
        MenuRechNom = new javax.swing.JMenuItem();
        MenuPat = new javax.swing.JMenu();
        MenuCreaPat = new javax.swing.JMenuItem();
        MenuRechPat = new javax.swing.JMenuItem();
        MenuRechNomPat = new javax.swing.JMenuItem();
        MenuPres = new javax.swing.JMenu();
        MenuCreaPres = new javax.swing.JMenuItem();
        MenuRechPres = new javax.swing.JMenuItem();
        PresRechPat = new javax.swing.JMenuItem();
        RechMedNom = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());
        getContentPane().add(creaMed23, "cardCreaMed");
        getContentPane().add(menuPrinc1, "card3");
        getContentPane().add(rechMed1, "card4");
        getContentPane().add(rechMedNom1, "cardRechMedNom");
        getContentPane().add(creaPat1, "cardCreaPat");
        getContentPane().add(creaPres1, "cardCreaPres");
        getContentPane().add(rechPat1, "cardRechPat");
        rechPat1.getAccessibleContext().setAccessibleDescription("");

        getContentPane().add(rechPatNom1, "cardRechNomPat");
        getContentPane().add(rechPres1, "cardRechPres");
        getContentPane().add(rechNomPat1, "CardNomPat");

        MenuMed.setText("Médecin");

        MenuMedCrea.setText("Creation");
        MenuMedCrea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuMedCreaActionPerformed(evt);
            }
        });
        MenuMed.add(MenuMedCrea);

        RechMed.setText("Recherche");
        RechMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RechMedActionPerformed(evt);
            }
        });
        MenuMed.add(RechMed);

        MenuRechNom.setText("Recherche Nom");
        MenuRechNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuRechNomActionPerformed(evt);
            }
        });
        MenuMed.add(MenuRechNom);

        jMenuBar1.add(MenuMed);

        MenuPat.setText("Patient");

        MenuCreaPat.setText("Création");
        MenuCreaPat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCreaPatActionPerformed(evt);
            }
        });
        MenuPat.add(MenuCreaPat);

        MenuRechPat.setText("Recherche");
        MenuRechPat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuRechPatActionPerformed(evt);
            }
        });
        MenuPat.add(MenuRechPat);

        MenuRechNomPat.setText("Recherche Nom");
        MenuRechNomPat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuRechNomPatActionPerformed(evt);
            }
        });
        MenuPat.add(MenuRechNomPat);

        jMenuBar1.add(MenuPat);

        MenuPres.setText("Prescription");

        MenuCreaPres.setText("Création");
        MenuCreaPres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCreaPresActionPerformed(evt);
            }
        });
        MenuPres.add(MenuCreaPres);

        MenuRechPres.setText("Recherche");
        MenuRechPres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuRechPresActionPerformed(evt);
            }
        });
        MenuPres.add(MenuRechPres);

        PresRechPat.setText("Recherche Patient");
        PresRechPat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PresRechPatActionPerformed(evt);
            }
        });
        MenuPres.add(PresRechPat);

        RechMedNom.setText("Recherche Médecin");
        RechMedNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RechMedNomActionPerformed(evt);
            }
        });
        MenuPres.add(RechMedNom);

        jMenuBar1.add(MenuPres);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RechMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RechMedActionPerformed
        cardl.show(this.getContentPane(), "card4");
    }//GEN-LAST:event_RechMedActionPerformed

    private void MenuMedCreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuMedCreaActionPerformed
        cardl.show(this.getContentPane(), "cardCreaMed");
    }//GEN-LAST:event_MenuMedCreaActionPerformed

    private void MenuRechNomPatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuRechNomPatActionPerformed
        cardl.show(this.getContentPane(), "CardNomPat");
    }//GEN-LAST:event_MenuRechNomPatActionPerformed

    private void MenuCreaPresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCreaPresActionPerformed
        cardl.show(this.getContentPane(), "cardCreaPres");    }//GEN-LAST:event_MenuCreaPresActionPerformed

    private void MenuRechNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuRechNomActionPerformed
        
    }//GEN-LAST:event_MenuRechNomActionPerformed

    private void MenuCreaPatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCreaPatActionPerformed
        cardl.show(this.getContentPane(), "cardCreaPat");
    }//GEN-LAST:event_MenuCreaPatActionPerformed

    private void MenuRechPatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuRechPatActionPerformed
        cardl.show(this.getContentPane(), "cardRechPat");
    }//GEN-LAST:event_MenuRechPatActionPerformed

    private void MenuRechPresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuRechPresActionPerformed
        cardl.show(this.getContentPane(), "cardRechPres");
    }//GEN-LAST:event_MenuRechPresActionPerformed

    private void PresRechPatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PresRechPatActionPerformed
        cardl.show(this.getContentPane(), "cardRechNomPat");
    }//GEN-LAST:event_PresRechPatActionPerformed

    private void RechMedNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RechMedNomActionPerformed
        cardl.show(this.getContentPane(), "cardRechMedNom");
    }//GEN-LAST:event_RechMedNomActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionPharma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionPharma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionPharma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionPharma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                gp.setVisible(true);
                cardl.show(gp.getContentPane(), "card3");
                gp.setSize(520, 460);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuCreaPat;
    private javax.swing.JMenuItem MenuCreaPres;
    private javax.swing.JMenu MenuMed;
    private javax.swing.JMenuItem MenuMedCrea;
    private javax.swing.JMenu MenuPat;
    private javax.swing.JMenu MenuPres;
    private javax.swing.JMenuItem MenuRechNom;
    private javax.swing.JMenuItem MenuRechNomPat;
    private javax.swing.JMenuItem MenuRechPat;
    private javax.swing.JMenuItem MenuRechPres;
    private javax.swing.JMenuItem PresRechPat;
    private javax.swing.JMenuItem RechMed;
    private javax.swing.JMenuItem RechMedNom;
    private Pharmacie.Graphique.CreaMed2 creaMed23;
    private Pharmacie.Graphique.CreaPat creaPat1;
    private Pharmacie.Graphique.CreaPres creaPres1;
    private javax.swing.JMenuBar jMenuBar1;
    private Pharmacie.Graphique.MenuPrinc menuPrinc1;
    private Pharmacie.Graphique.RechMed rechMed1;
    private Pharmacie.Graphique.RechMedNom rechMedNom1;
    private Pharmacie.Graphique.RechNomPat rechNomPat1;
    private Pharmacie.Graphique.RechPat rechPat1;
    private Pharmacie.Graphique.RechPatNom rechPatNom1;
    private Pharmacie.Graphique.RechPres rechPres1;
    // End of variables declaration//GEN-END:variables
}
