/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pharmacie.Graphique;

import Pharmacie.DAO.PatientDAO;
import Pharmacie.metier.Patient;
import javax.swing.JOptionPane;

/**
 *
 * @author hugo.delmarche
 */
public class RechPat extends javax.swing.JPanel {
    PatientDAO patdao = null;
    Patient p;

    /**
     * Creates new form CreaMed2
     */
    public RechPat() {
        initComponents();
        txtNomPat.setEditable(false);
        txtPrePat.setEditable(false);
        txtTelPat.setEditable(false);
        BtMajPat.setEnabled(false);
        BtDelPat.setEnabled(false);

    }
    
    public void setPatdao(PatientDAO patdao) {
        this.patdao = patdao;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        IdPat = new javax.swing.JLabel();
        NomPat = new javax.swing.JLabel();
        PrePat = new javax.swing.JLabel();
        TelPat = new javax.swing.JLabel();
        txtIdPat = new javax.swing.JTextField();
        txtNomPat = new javax.swing.JTextField();
        txtPrePat = new javax.swing.JTextField();
        txtTelPat = new javax.swing.JTextField();
        btRechPat = new javax.swing.JButton();
        BtMajPat = new javax.swing.JButton();
        BtDelPat = new javax.swing.JButton();
        btFin1 = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        IdPat.setText("identifiant");

        NomPat.setText("Nom");

        PrePat.setText("Prénom");

        TelPat.setText("Téléphone");

        btRechPat.setText("Recherche");
        btRechPat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRechPatActionPerformed(evt);
            }
        });

        BtMajPat.setText("Mise à jour");
        BtMajPat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtMajPatActionPerformed(evt);
            }
        });

        BtDelPat.setText("Suppression");
        BtDelPat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtDelPatActionPerformed(evt);
            }
        });

        btFin1.setText("Quitter");
        btFin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFin1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btRechPat, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtMajPat, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(BtDelPat)
                .addGap(18, 18, 18)
                .addComponent(btFin1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(17, 17, 17))
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PrePat, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtPrePat, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TelPat, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(IdPat, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                                .addComponent(NomPat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 236, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtIdPat)
                            .addComponent(txtNomPat)
                            .addComponent(txtTelPat, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE))))
                .addGap(71, 71, 71))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IdPat)
                    .addComponent(txtIdPat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNomPat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NomPat, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PrePat)
                    .addComponent(txtPrePat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TelPat, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtTelPat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btRechPat)
                    .addComponent(BtMajPat)
                    .addComponent(BtDelPat)
                    .addComponent(btFin1))
                .addGap(52, 52, 52))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btRechPatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRechPatActionPerformed
        try {
            int id = Integer.parseInt(txtIdPat.getText());
            p = patdao.read(id);
            txtNomPat.setText(p.getNom());
            txtPrePat.setText(p.getPrenom());
            txtTelPat.setText(p.getTel());
            BtMajPat.setEnabled(true);
            BtDelPat.setEnabled(true);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "ERREUR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btRechPatActionPerformed

    private void BtMajPatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtMajPatActionPerformed
        if (txtIdPat.isEditable()) {
            txtIdPat.setEditable(false);
            txtNomPat.setEditable(true);
            txtPrePat.setEditable(true);
            txtTelPat.setEditable(true);
            JOptionPane.showMessageDialog(this, "Modifier les champs que vous souhaitez mettre à jour puis cliquer à nouveau sur Mise à jour", "Mise à jour", JOptionPane.INFORMATION_MESSAGE);
        } else {
            try {
                p.setNom(txtNomPat.getText());
                p.setPrenom(txtPrePat.getText());
                p.setTel(txtTelPat.getText());
                patdao.update(p);
                JOptionPane.showMessageDialog(this, "Patient mis à jour", "succès", JOptionPane.INFORMATION_MESSAGE);
                txtIdPat.setEditable(true);
                txtNomPat.setEditable(false);
                txtPrePat.setEditable(false);
                txtTelPat.setEditable(false);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage(), "ERREUR", JOptionPane.ERROR_MESSAGE);
            }
        }

    }//GEN-LAST:event_BtMajPatActionPerformed

    private void BtDelPatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtDelPatActionPerformed
        try {
            patdao.delete(p);
            JOptionPane.showMessageDialog(this, "Patient supprimer", "succès", JOptionPane.INFORMATION_MESSAGE);
            txtIdPat.setText(" ");
            txtNomPat.setText(" ");
            txtPrePat.setText(" ");
            txtTelPat.setText(" ");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "ERREUR", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_BtDelPatActionPerformed

    private void btFin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFin1ActionPerformed
        JOptionPane.showMessageDialog(this, "Au revoir", "Fermeture", JOptionPane.INFORMATION_MESSAGE);
        System.exit(0);
    }//GEN-LAST:event_btFin1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtDelPat;
    private javax.swing.JButton BtMajPat;
    private javax.swing.JLabel IdPat;
    private javax.swing.JLabel NomPat;
    private javax.swing.JLabel PrePat;
    private javax.swing.JLabel TelPat;
    private javax.swing.JButton btFin1;
    private javax.swing.JButton btRechPat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtIdPat;
    private javax.swing.JTextField txtNomPat;
    private javax.swing.JTextField txtPrePat;
    private javax.swing.JTextField txtTelPat;
    // End of variables declaration//GEN-END:variables
}
