/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pharmacie.Graphique;

import Pharmacie.DAO.PatientDAO;
import Pharmacie.metier.Patient;
import javax.swing.JOptionPane;

/**
 *
 * @author hugo.delmarche
 */
public class RechPat extends javax.swing.JPanel {

    PatientDAO patdao = null;
    Patient p;

    /**
     * Creates new form CreaMed2
     */
    public RechPat() {
        initComponents();
        txtNomPat.setEditable(false);
        txtPrePat.setEditable(false);
        txtTelPat.setEditable(false);
        BtMajPat.setEnabled(false);
        BtDelPat.setEnabled(false);

    }

    public void setMeddao(PatientDAO presdao) {
        this.patdao = presdao;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        IdPat = new javax.swing.JLabel();
        NomPat = new javax.swing.JLabel();
        PrePat = new javax.swing.JLabel();
        TelPat = new javax.swing.JLabel();
        txtIdPat = new javax.swing.JTextField();
        txtNomPat = new javax.swing.JTextField();
        txtPrePat = new javax.swing.JTextField();
        txtTelPat = new javax.swing.JTextField();
        btRechPat = new javax.swing.JButton();
        btRetour = new javax.swing.JButton();
        BtMajPat = new javax.swing.JButton();
        BtDelPat = new javax.swing.JButton();
        AffPresPat = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        IdPat.setText("identifiant");

        NomPat.setText("Nom");

        PrePat.setText("Prénom");

        TelPat.setText("Téléphone");

        btRechPat.setText("Recherche");
        btRechPat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRechPatActionPerformed(evt);
            }
        });

        btRetour.setText("Retour");
        btRetour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRetourActionPerformed(evt);
            }
        });

        BtMajPat.setText("Mise à jour");
        BtMajPat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtMajPatActionPerformed(evt);
            }
        });

        BtDelPat.setText("Suppression");
        BtDelPat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtDelPatActionPerformed(evt);
            }
        });

        AffPresPat.setText("Afficher prescription");
        AffPresPat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AffPresPatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(IdPat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(NomPat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PrePat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TelPat, javax.swing.GroupLayout.PREFERRED_SIZE, 57, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(AffPresPat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btRechPat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BtDelPat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtMajPat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btRetour)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtIdPat)
                        .addComponent(txtNomPat)
                        .addComponent(txtPrePat)
                        .addComponent(txtTelPat, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)))
                .addGap(71, 71, 71))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdPat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IdPat))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NomPat)
                    .addComponent(txtNomPat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PrePat)
                    .addComponent(txtPrePat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TelPat)
                    .addComponent(txtTelPat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btRechPat)
                            .addComponent(BtMajPat))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtDelPat)
                            .addComponent(AffPresPat)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(btRetour)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btRechPatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRechPatActionPerformed
        try {
            int id = Integer.parseInt(txtIdPat.getText());
            p = patdao.read(id);
            txtNomPat.setText(p.getNom());
            txtPrePat.setText(p.getPrenom());
            txtTelPat.setText(p.getTel());
            BtMajPat.setEnabled(true);
            BtDelPat.setEnabled(true);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "ERREUR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btRechPatActionPerformed

    private void btRetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRetourActionPerformed

    }//GEN-LAST:event_btRetourActionPerformed

    private void BtMajPatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtMajPatActionPerformed
        if (txtIdPat.isEditable()) {
            txtIdPat.setEditable(false);
            txtNomPat.setEditable(true);
            txtPrePat.setEditable(true);
            txtTelPat.setEditable(true);
            JOptionPane.showMessageDialog(this, "Modifier les champs que vous souhaitez mettre à jour puis cliquer à nouveau sur Mise à jour", "Mise à jour", JOptionPane.INFORMATION_MESSAGE);
        } else {
            try {
                p.setNom(txtNomPat.getText());
                p.setPrenom(txtPrePat.getText());
                p.setTel(txtTelPat.getText());
                patdao.update(p);
                JOptionPane.showMessageDialog(this, "Patient mis à jour", "succès", JOptionPane.INFORMATION_MESSAGE);
                txtIdPat.setEditable(true);
                txtNomPat.setEditable(false);
                txtPrePat.setEditable(false);
                txtTelPat.setEditable(false);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage(), "ERREUR", JOptionPane.ERROR_MESSAGE);
            }
        }

    }//GEN-LAST:event_BtMajPatActionPerformed

    private void BtDelPatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtDelPatActionPerformed
        try {
            patdao.delete(p);
            JOptionPane.showMessageDialog(this, "Patient supprimer", "succès", JOptionPane.INFORMATION_MESSAGE);
            txtIdPat.setText(" ");
            txtNomPat.setText(" ");
            txtPrePat.setText(" ");
            txtTelPat.setText(" ");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "ERREUR", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_BtDelPatActionPerformed

    private void AffPresPatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AffPresPatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AffPresPatActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AffPresPat;
    private javax.swing.JButton BtDelPat;
    private javax.swing.JButton BtMajPat;
    private javax.swing.JLabel IdPat;
    private javax.swing.JLabel NomPat;
    private javax.swing.JLabel PrePat;
    private javax.swing.JLabel TelPat;
    private javax.swing.JButton btRechPat;
    private javax.swing.JButton btRetour;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtIdPat;
    private javax.swing.JTextField txtNomPat;
    private javax.swing.JTextField txtPrePat;
    private javax.swing.JTextField txtTelPat;
    // End of variables declaration//GEN-END:variables
}
