/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pharmacie.Graphique;

import Pharmacie.DAO.PrescriptionDAO;
import Pharmacie.metier.Prescription;
import javax.swing.JOptionPane;

/**
 *
 * @author hugo.delmarche
 */
public class RechPres extends javax.swing.JPanel {

    PrescriptionDAO presdao = null;
    Prescription p;

    /**
     * Creates new form CreaMed2
     */
    public RechPres() {
        initComponents();
        txtDatPres.setEditable(false);
        txtIdMedPres.setEditable(false);
        txtIdPatPres.setEditable(false);
        BtMajPres.setEnabled(false);
        BtDelPres.setEnabled(false);

    }

    public void setMeddao(PrescriptionDAO presdao) {
        this.presdao = presdao;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        IdPat = new javax.swing.JLabel();
        DatePres = new javax.swing.JLabel();
        IdMedPres = new javax.swing.JLabel();
        IdPatPres = new javax.swing.JLabel();
        txtIdPat = new javax.swing.JTextField();
        txtDatPres = new javax.swing.JTextField();
        txtIdMedPres = new javax.swing.JTextField();
        txtIdPatPres = new javax.swing.JTextField();
        btRechPres = new javax.swing.JButton();
        btRetour = new javax.swing.JButton();
        BtMajPres = new javax.swing.JButton();
        BtDelPres = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        IdPat.setText("identifiant");

        DatePres.setText("Date prescription");

        IdMedPres.setText("Identifiant Médecin");

        IdPatPres.setText("Identifiant Patient");

        btRechPres.setText("Recherche");
        btRechPres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRechPresActionPerformed(evt);
            }
        });

        btRetour.setText("Retour");
        btRetour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRetourActionPerformed(evt);
            }
        });

        BtMajPres.setText("Mise à jour");
        BtMajPres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtMajPresActionPerformed(evt);
            }
        });

        BtDelPres.setText("Suppression");
        BtDelPres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtDelPresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(IdPat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DatePres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(IdMedPres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(IdPatPres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtIdPat)
                    .addComponent(txtDatPres)
                    .addComponent(txtIdMedPres)
                    .addComponent(txtIdPatPres, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE))
                .addGap(71, 71, 71))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btRechPres)
                .addGap(18, 18, 18)
                .addComponent(BtMajPres)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(BtDelPres)
                .addGap(18, 18, 18)
                .addComponent(btRetour)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdPat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IdPat))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DatePres)
                    .addComponent(txtDatPres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(IdMedPres)
                    .addComponent(txtIdMedPres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IdPatPres)
                    .addComponent(txtIdPatPres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btRechPres)
                    .addComponent(btRetour)
                    .addComponent(BtMajPres)
                    .addComponent(BtDelPres))
                .addContainerGap(20, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btRechPresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRechPresActionPerformed
        try {
            int id = Integer.parseInt(txtIdPat.getText());
            p = presdao.read(id);
            txtDatPres.setText(p.getDate());
            txtIdMedPres.setText(Integer.toString(p.getIdmed()));
            txtIdPatPres.setText(Integer.toString(p.getIdpat()));
            BtMajPres.setEnabled(true);
            BtDelPres.setEnabled(true);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "ERREUR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btRechPresActionPerformed

    private void btRetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRetourActionPerformed

    }//GEN-LAST:event_btRetourActionPerformed

    private void BtMajPresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtMajPresActionPerformed
        if (txtIdPat.isEditable()) {
            txtIdPat.setEditable(false);
            txtDatPres.setEditable(true);
            txtIdMedPres.setEditable(true);
            txtIdPatPres.setEditable(true);
            JOptionPane.showMessageDialog(this, "Modifier les champs que vous souhaitez mettre à jour puis cliquer à nouveau sur Mise à jour", "Mise à jour", JOptionPane.INFORMATION_MESSAGE);
        } else {
            try {
                p.setDate(txtDatPres.getText());
                p.setIdmed(Integer.parseInt(txtIdMedPres.getText()));
                p.setIdpat(Integer.parseInt(txtIdPatPres.getText()));
                presdao.update(p);
                JOptionPane.showMessageDialog(this, "Prescription mise à jour", "succès", JOptionPane.INFORMATION_MESSAGE);
                txtIdPat.setEditable(true);
                txtDatPres.setEditable(false);
                txtIdMedPres.setEditable(false);
                txtIdPatPres.setEditable(false);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage(), "ERREUR", JOptionPane.ERROR_MESSAGE);
            }
        }

    }//GEN-LAST:event_BtMajPresActionPerformed

    private void BtDelPresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtDelPresActionPerformed
        try {
            presdao.delete(p);
            JOptionPane.showMessageDialog(this, "Patient supprimer", "succès", JOptionPane.INFORMATION_MESSAGE);
            txtIdPat.setText(" ");
            txtDatPres.setText(" ");
            txtIdMedPres.setText(" ");
            txtIdPatPres.setText(" ");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "ERREUR", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_BtDelPresActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtDelPres;
    private javax.swing.JButton BtMajPres;
    private javax.swing.JLabel DatePres;
    private javax.swing.JLabel IdMedPres;
    private javax.swing.JLabel IdPat;
    private javax.swing.JLabel IdPatPres;
    private javax.swing.JButton btRechPres;
    private javax.swing.JButton btRetour;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtDatPres;
    private javax.swing.JTextField txtIdMedPres;
    private javax.swing.JTextField txtIdPat;
    private javax.swing.JTextField txtIdPatPres;
    // End of variables declaration//GEN-END:variables
}
